# Generated by Django 3.1.3 on 2021-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_registration', models.BooleanField(default=True)),
                ('term', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pr', models.CharField(max_length=25)),
                ('surname_pr', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=64)),
                ('run_distance', models.IntegerField()),
                ('run_date', models.DateField()),
                ('run_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RunReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=25)),
                ('run_city', models.CharField(max_length=25)),
                ('run_date', models.DateField()),
                ('run_distance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
