# Generated by Django 3.1.3 on 2021-01-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration', models.BooleanField(default=True)),
                ('term', models.DateField()),
            ],
        ),
    ]
