# Generated by Django 3.1.3 on 2021-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtype',
            name='type',
            field=models.CharField(default='ultra', max_length=20),
        ),
    ]
