# Generated by Django 3.1.3 on 2021-01-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Runs',
            new_name='run_table',
        ),
    ]
