# Generated by Django 3.1.3 on 2021-03-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='runs.userprivatedata'),
        ),
        migrations.AddField(
            model_name='registration',
            name='enrolledPeople',
            field=models.ManyToManyField(to='runs.AllRuns'),
        ),
        migrations.AddField(
            model_name='userprivatedata',
            name='run_payment',
            field=models.BooleanField(default=False),
        ),
    ]
