# Generated by Django 3.1.3 on 2021-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20210320_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='EC',
            field=models.IntegerField(),
        ),
    ]
