# Generated by Django 3.1.3 on 2021-01-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20210102_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='run_table',
            new_name='Main',
        ),
    ]
