# Generated by Django 3.1.3 on 2021-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_auto_20210103_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanceOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.IntegerField()),
                ('medium', models.IntegerField()),
                ('marathon', models.IntegerField()),
                ('ultra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_s', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_l', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_u', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RunReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
