# Generated by Django 3.1.3 on 2021-01-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_awards_distanceoptions_payment_runreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pr', models.CharField(max_length=25)),
                ('surname_pr', models.CharField(max_length=25)),
                ('date_of_birth_pr', models.DateField()),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('run_enroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.main')),
            ],
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='DistanceOptions',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
