# Generated by Django 3.1.3 on 2021-01-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_auto_20210106_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=25)),
                ('run_city', models.CharField(max_length=25)),
                ('run_date', models.DateField()),
                ('run_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
    ]
